/* LOADING ACTIONS */
export const APP_LOADING = 'APP_LOADING';

/* NETWORK LOADING ACTION */
export const LOADING = 'LOADING';

/* THEME ACTION */
export const SET_DARK_THEME = 'SET_DARK_THEME';
export const SET_LIGHT_THEME = 'SET_LIGHT_THEME';
export const THEME_CHANGE_LIGHT = 'THEME_CHANGE_LIGHT';
export const THEME_CHANGE_DARK = 'THEME_CHANGE_DARK';

/* HOME ACTIONS */
export const HOME_GET_DASHBORD_DATA = 'HOME_GET_DASHBORD_DATA';

/* STORAGE ACTION */
export const STOREGE_INSERT_HISTORY_DATA = 'STOREGE_INSERT_HISTORY_DATA';
export const STOREGE_READ_HISTORY_DATA = 'STOREGE_READ_HISTORY_DATA';
export const STOREGE_CLEAR_HISTORY_DATA = 'STOREGE_CLEAR_HISTORY_DATA';